version: '3'

services:
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - database.env
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer_media
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  db:
    driver: local